const SUPABASE_URL='https://ralqeebyjbhkrzuvqyyw.supabase.co';
const SUPABASE_KEY='sb_publishable_OKVdVUkerbvWXVeYJUqYqw_Xij3f9L8';
const db=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let session=null,me=null,role='customer',screen='home';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const products=[{name:'Fit Shakti Weight Loss',type:'weight_loss'},{name:'Fit Shakti Weight Gain',type:'weight_gain'}];
function login(){app.innerHTML=`<main class="login"><section class="box"><img src="assets/icon.svg" class="logo"><h1>Fit Shakti</h1><p>Stronger You Naturally.</p><input id="name" placeholder="Full name for new account"><input id="email" type="email" placeholder="Email"><input id="password" type="password" placeholder="Password (6+ characters)"><div class="actions"><button onclick="signin()">Sign in</button><button class="light" onclick="signup()">Create account</button></div><small>Customer accounts are created by default. Admin access is controlled securely in Supabase.</small></section></main>`}
async function signup(){const name=document.getElementById('name').value.trim(),email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;if(!name||!email||password.length<6)return alert('Enter name, email and a password of at least 6 characters.');const {data,error}=await db.auth.signUp({email,password,options:{data:{full_name:name}}});if(error)return alert(error.message);if(!data.session)return alert('Account created. Check your email if verification is enabled, then sign in.');await boot()}
async function signin(){const email=document.getElementById('email').value.trim(),password=document.getElementById('password').value;const {error}=await db.auth.signInWithPassword({email,password});if(error)return alert(error.message);await boot()}
async function signout(){await db.auth.signOut();session=null;me=null;login()}
async function boot(){const {data:{session:s}}=await db.auth.getSession();session=s;if(!session)return login();const {data,error}=await db.from('profiles').select('*').eq('id',session.user.id).single();if(error)return alert(error.message);me=data;role=data.role;screen=role==='admin'?'dashboard':'home';render()}
function layout(body){const nav=role==='admin'?[['dashboard','Dashboard'],['customers','Customers'],['orders','Orders'],['products','Products']]:[['home','Home'],['products','Products'],['log','Log'],['orders','Orders'],['profile','Profile']];return `<div class="shell"><header><div class="brand"><img src="assets/icon.svg">Fit Shakti</div><div><span class="tag">${role}</span><button class="small" onclick="signout()">Sign out</button></div></header><main>${body}</main><nav>${nav.map(([id,t])=>`<button class="${screen===id?'active':''}" onclick="go('${id}')">${t}</button>`).join('')}</nav></div>`}
function home(){return `<section class="hero"><div><h1>Hello, ${esc(me?.full_name||'Customer')}</h1><p>Track your routine, stay consistent and follow your Fit Shakti journey.</p></div>🌿</section><div class="grid"><div class="card"><small>Weight</small><b>${me?.current_weight_kg||'--'} kg</b></div><div class="card"><small>Goal</small><b>${String(me?.goal||'Not set').replace('_',' ')}</b></div><div class="card"><small>Water</small><b>Log daily</b></div><div class="card"><small>Steps</small><b>Log daily</b></div></div><div class="card"><h2>Quick log</h2><div class="actions"><button onclick="go('log')">Log food</button><button onclick="addWater()">+250 ml water</button><button class="light" onclick="go('products')">Shop powder</button></div></div>`}
async function productsPage(){const {data}=await db.from('products').select('*').eq('active',true).order('name');const list=data?.length?data:products;return `<h1>Fit Shakti Powders</h1><div class="cards">${list.map(p=>`<article class="card"><div class="jar">FIT<br>SHAKTI</div><span class="tag">${p.product_type==='weight_gain'?'Weight Gain':'Weight Loss'}</span><h2>${esc(p.name)}</h2><p>${esc(p.description||'Product details and usage guidance')}</p><b>${p.price?'₹'+p.price:'Price to be configured'}</b><div class="actions"><button onclick="buy('${p.id||''}')">Order</button></div></article>`).join('')}</div>`}
async function buy(id){if(!id)return alert('Admin needs to configure product price first.');const {data:p}=await db.from('products').select('*').eq('id',id).single();if(!p)return;const {data:o,error}=await db.from('orders').insert({customer_id:session.user.id,subtotal:p.price,shipping_amount:0,total_amount:p.price,shipping_address:me?.address||{}}).select().single();if(error)return alert(error.message);const {error:e}=await db.from('order_items').insert({order_id:o.id,product_id:p.id,quantity:1,unit_price:p.price,total_price:p.price});if(e)return alert(e.message);alert('Order placed.');go('orders')}
async function orders(){const {data}=await db.from('orders').select('id,status,total_amount,created_at,order_items(product_id,quantity,unit_price)').eq('customer_id',session.user.id).order('created_at',{ascending:false});return `<h1>Orders</h1><div class="list">${(data||[]).map(o=>`<div class="card"><b>#${o.id.slice(0,8)}</b> <span class="tag">${o.status}</span><p>₹${o.total_amount} · ${new Date(o.created_at).toLocaleDateString()}</p></div>`).join('')||'<div class="card">No orders yet.</div>'}</div>`}
function logPage(){return `<h1>Log Today</h1><div class="cards"><section class="card"><h2>Water</h2><button onclick="addWater()">+250 ml</button></section><section class="card"><h2>Food</h2><input id="meal" placeholder="Meal"><input id="food" placeholder="Food name"><input id="qty" placeholder="Quantity"><button onclick="saveFood()">Save food log</button></section><section class="card"><h2>Powder intake</h2><select id="powder"><option value="weight_loss">Weight Loss</option><option value="weight_gain">Weight Gain</option></select><input id="serve" value="1 serving" placeholder="Serving"><button onclick="savePowder()">Save powder log</button></section><section class="card"><h2>Steps</h2><input id="steps" type="number" placeholder="Today's steps"><button onclick="saveSteps()">Save steps</button></section></div>`}
async function addWater(){const {error}=await db.from('water_logs').insert({customer_id:session.user.id,amount_ml:250});if(error)return alert(error.message);alert('250 ml added.');render()}
async function saveFood(){const {error}=await db.from('food_logs').insert({customer_id:session.user.id,meal_type:document.getElementById('meal').value||'Other',food_name:document.getElementById('food').value||'Food',quantity:document.getElementById('qty').value});if(error)return alert(error.message);alert('Food logged.');go('home')}
async function savePowder(){const {data:p}=await db.from('products').select('id').eq('product_type',document.getElementById('powder').value).limit(1).maybeSingle();const {error}=await db.from('powder_logs').insert({customer_id:session.user.id,product_id:p?.id||null,quantity:document.getElementById('serve').value});if(error)return alert(error.message);alert('Powder intake logged.');go('home')}
async function saveSteps(){const n=Number(document.getElementById('steps').value||0);const {error}=await db.from('step_logs').upsert({customer_id:session.user.id,steps:n,source:'manual',logged_on:new Date().toISOString().slice(0,10)},{onConflict:'customer_id,logged_on,source'});if(error)return alert(error.message);alert('Steps saved.');go('home')}
async function profile(){return `<h1>Profile</h1><section class="card"><input id="fullName" value="${esc(me?.full_name)}" placeholder="Full name"><input id="phone" value="${esc(me?.phone)}" placeholder="Phone"><select id="goal"><option value="weight_loss">Weight Loss</option><option value="weight_gain">Weight Gain</option><option value="maintenance">Maintenance</option></select><input id="weight" type="number" value="${me?.current_weight_kg||''}" placeholder="Current weight kg"><button onclick="saveProfile()">Save profile</button></section>`}
async function saveProfile(){const {data,error}=await db.from('profiles').update({full_name:document.getElementById('fullName').value,phone:document.getElementById('phone').value,goal:document.getElementById('goal').value,current_weight_kg:Number(document.getElementById('weight').value)||null}).eq('id',session.user.id).select().single();if(error)return alert(error.message);me=data;alert('Profile saved.');render()}
async function adminDashboard(){const [{count:c},{count:o}]=await Promise.all([db.from('profiles').select('*',{count:'exact',head:true}).eq('role','customer'),db.from('orders').select('*',{count:'exact',head:true})]);return `<section class="hero"><div><h1>Fit Shakti Control Center</h1><p>Admin dashboard</p></div>📊</section><div class="grid"><div class="card"><small>Customers</small><b>${c||0}</b></div><div class="card"><small>Orders</small><b>${o||0}</b></div></div>`}
async function customers(){const {data,error}=await db.from('profiles').select('id,full_name,phone,goal,current_weight_kg,created_at').eq('role','customer').order('created_at',{ascending:false});if(error)return `<div class="card">${esc(error.message)}</div>`;return `<h1>Customers</h1><div class="list">${(data||[]).map(c=>`<div class="card"><b>${esc(c.full_name||'Unnamed')}</b><p>${esc(c.phone||'')} · ${esc(c.goal||'')} · ${c.current_weight_kg||'--'} kg</p></div>`).join('')||'<div class="card">No customers yet.</div>'}</div>`}
async function adminOrders(){const {data}=await db.from('orders').select('id,status,total_amount,created_at,customer_id,profiles(full_name)').order('created_at',{ascending:false});return `<h1>Orders</h1><div class="list">${(data||[]).map(o=>`<div class="card"><b>#${o.id.slice(0,8)}</b> <span class="tag">${o.status}</span><p>${esc(o.profiles?.full_name||'Customer')} · ₹${o.total_amount}</p></div>`).join('')||'<div class="card">No orders.</div>'}</div>`}
async function adminProducts(){const {data}=await db.from('products').select('*').order('name');return `<h1>Products</h1><div class="cards">${(data||[]).map(p=>`<article class="card"><span class="tag">${p.product_type}</span><h2>${esc(p.name)}</h2><p>₹${p.price} · Stock ${p.stock_qty}</p><p class="muted">FSSAI: ${esc(p.fssai_license||'Not set')}</p></article>`).join('')}</div>`}
async function render(){let body='';if(role==='admin'){if(screen==='dashboard')body=await adminDashboard();else if(screen==='customers')body=await customers();else if(screen==='orders')body=await adminOrders();else if(screen==='products')body=await adminProducts()}else{if(screen==='home')body=home();else if(screen==='products')body=await productsPage();else if(screen==='orders')body=await orders();else if(screen==='log')body=logPage();else body=await profile()}app.innerHTML=layout(body)}
function go(s){screen=s;render()}
window.addEventListener('load',boot);db.auth.onAuthStateChange(()=>setTimeout(boot,0));